version: '1'
services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altmetric-badge-docs
    stdin_open: true
    tty: true
    volumes:
      - .:/docs
    ports:
      - 8000:8000
